package com.ecom.app.enums;

public enum OrderStatus {

	ORDER_PLACED,
	SELLER_ACCEPTED_ORDER,
	ITEM_SHIPPED,
	SELLER_REJECTED_ORDER,
	PRODUCT_OUT_FROM_SELLER_HUB,
	ORDER_ON_THE_WAY,
	ORDER_ARRIVED_TO_NEAREST_HUB,
	ORDER_HANDOVER_TO_COURIER_BOY,
	ORDER_OUT_FOR_DELIVERY,
	ORDER_DELIVERED,
	ORDER_CANCELLED_BY_USER
	
}
